Add help message and binary check to `flatpak-alias`

diff --git a/scripts/flatpak-alias b/scripts/flatpak-alias
--- a/scripts/flatpak-alias
+++ b/scripts/flatpak-alias
@@ -1,7 +1,20 @@
-#!/bin/sh
-# USAGE: ./flatpak-alias >> /path/to/bashrc/or/zshrc
+#!/bin/bash
 
-echo "# Flatpak aliases"
+help_msg="USAGE:
+    run './flatpak-alias > /path/to/file'
+    then add 'source /path/to/file' inside your bashrc or zshrc"
+
+if echo "$1" | grep -Eq "^(-h|--help)$"; then
+    echo "$help_msg"
+    exit
+fi
+
+if ! command -v flatpak &>/dev/null; then
+    echo "Error: flatpak is not installed" >&2
+    exit 1
+fi
+
+echo "# Flatpak aliases (generated by 'flatpak-alias' script)"
 
 # For each flatpak installed (apps only), automatically create a shell alias
 flatpak list --app | while read -r line; do
